### ISSUE TITLE
Just read your article on neomutt

### ISSUE THREAD

**Issue by charbelsako** [webgefrickel/dotfiles#1]
How would you create the certificates file on linux. Do you have any idea. I just got to the part where i test mbsync and msmtp and it didn't work

**Comment by charbelsako** [comment]
Fixed mbsync. all that's left is msmtp

**Comment by webgefrickel** [comment]
I don't really have an idea how to accomplish this under linux. But if you have mbsync up an running (and thus a working certificates-file?) you should be able to provide this config in .msmtprc with:

`tls_trust_file ~/dotfiles/office/certificates.crt`

for every account, see: https://github.com/webgefrickel/dotfiles/blob/master/office/msmtprc

**Comment by charbelsako** [comment]
Figured it out in the end. Just added my password. I don't have a trust file
